/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq;


import com.topscore.omnichannel.order.jooq.tables.Databasechangelog;
import com.topscore.omnichannel.order.jooq.tables.Databasechangeloglock;
import com.topscore.omnichannel.order.jooq.tables.Goods;
import com.topscore.omnichannel.order.jooq.tables.OrderGoods;
import com.topscore.omnichannel.order.jooq.tables.Orders;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order extends SchemaImpl {

    private static final long serialVersionUID = 1019766383;

    /**
     * The reference instance of <code>order</code>
     */
    public static final Order ORDER = new Order();

    /**
     * The table <code>order.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = com.topscore.omnichannel.order.jooq.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>order.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = com.topscore.omnichannel.order.jooq.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * 商品表
     */
    public final Goods GOODS = com.topscore.omnichannel.order.jooq.tables.Goods.GOODS;

    /**
     * 订单表
     */
    public final Orders ORDERS = com.topscore.omnichannel.order.jooq.tables.Orders.ORDERS;

    /**
     * 订单商品表
     */
    public final OrderGoods ORDER_GOODS = com.topscore.omnichannel.order.jooq.tables.OrderGoods.ORDER_GOODS;

    /**
     * No further instances allowed
     */
    private Order() {
        super("order", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Goods.GOODS,
            Orders.ORDERS,
            OrderGoods.ORDER_GOODS);
    }
}
