/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq.tables;


import com.topscore.omnichannel.order.jooq.Order;
import com.topscore.omnichannel.order.jooq.tables.records.GoodsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * 商品表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Goods extends TableImpl<GoodsRecord> {

    private static final long serialVersionUID = 2140052335;

    /**
     * The reference instance of <code>order.goods</code>
     */
    public static final Goods GOODS = new Goods();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoodsRecord> getRecordType() {
        return GoodsRecord.class;
    }

    /**
     * The column <code>order.goods.id</code>. 商品编号
     */
    public final TableField<GoodsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "商品编号");

    /**
     * The column <code>order.goods.name</code>. 商品名称
     */
    public final TableField<GoodsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "商品名称");

    /**
     * Create a <code>order.goods</code> table reference
     */
    public Goods() {
        this("goods", null);
    }

    /**
     * Create an aliased <code>order.goods</code> table reference
     */
    public Goods(String alias) {
        this(alias, GOODS);
    }

    private Goods(String alias, Table<GoodsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Goods(String alias, Table<GoodsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "商品表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Order.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Goods as(String alias) {
        return new Goods(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Goods rename(String name) {
        return new Goods(name, null);
    }
}
