/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq;


import com.topscore.omnichannel.order.jooq.tables.Goods;
import com.topscore.omnichannel.order.jooq.tables.Member;
import com.topscore.omnichannel.order.jooq.tables.Order;
import com.topscore.omnichannel.order.jooq.tables.OrderGoods;
import com.topscore.omnichannel.order.jooq.tables.OrderMessage;
import com.topscore.omnichannel.order.jooq.tables.records.GoodsRecord;
import com.topscore.omnichannel.order.jooq.tables.records.MemberRecord;
import com.topscore.omnichannel.order.jooq.tables.records.OrderGoodsRecord;
import com.topscore.omnichannel.order.jooq.tables.records.OrderMessageRecord;
import com.topscore.omnichannel.order.jooq.tables.records.OrderRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>order</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GoodsRecord> KEY_GOODS_PRIMARY = UniqueKeys0.KEY_GOODS_PRIMARY;
    public static final UniqueKey<MemberRecord> KEY_MEMBER_PRIMARY = UniqueKeys0.KEY_MEMBER_PRIMARY;
    public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = UniqueKeys0.KEY_ORDER_PRIMARY;
    public static final UniqueKey<OrderGoodsRecord> KEY_ORDER_GOODS_PRIMARY = UniqueKeys0.KEY_ORDER_GOODS_PRIMARY;
    public static final UniqueKey<OrderMessageRecord> KEY_ORDER_MESSAGE_PRIMARY = UniqueKeys0.KEY_ORDER_MESSAGE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrderRecord, MemberRecord> FK414GUCUR8MOYN7OVP39VXKPMY = ForeignKeys0.FK414GUCUR8MOYN7OVP39VXKPMY;
    public static final ForeignKey<OrderGoodsRecord, OrderRecord> FKIO4DNP4A0HXMD2C1VJAO7VYT7 = ForeignKeys0.FKIO4DNP4A0HXMD2C1VJAO7VYT7;
    public static final ForeignKey<OrderGoodsRecord, GoodsRecord> FK7IG6A3V9C9ALUSUPY6OYXLFOW = ForeignKeys0.FK7IG6A3V9C9ALUSUPY6OYXLFOW;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<GoodsRecord> KEY_GOODS_PRIMARY = createUniqueKey(Goods.GOODS, "KEY_goods_PRIMARY", Goods.GOODS.NUMBER);
        public static final UniqueKey<MemberRecord> KEY_MEMBER_PRIMARY = createUniqueKey(Member.MEMBER, "KEY_member_PRIMARY", Member.MEMBER.NUMBER);
        public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = createUniqueKey(Order.ORDER_, "KEY_order_PRIMARY", Order.ORDER_.NUMBER, Order.ORDER_.WRITE_OFF);
        public static final UniqueKey<OrderGoodsRecord> KEY_ORDER_GOODS_PRIMARY = createUniqueKey(OrderGoods.ORDER_GOODS, "KEY_order_goods_PRIMARY", OrderGoods.ORDER_GOODS.ORDER_NUMBER, OrderGoods.ORDER_GOODS.ORDER_WRITE_OFF, OrderGoods.ORDER_GOODS.GOODS_NUMBER);
        public static final UniqueKey<OrderMessageRecord> KEY_ORDER_MESSAGE_PRIMARY = createUniqueKey(OrderMessage.ORDER_MESSAGE, "KEY_order_message_PRIMARY", OrderMessage.ORDER_MESSAGE.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<OrderRecord, MemberRecord> FK414GUCUR8MOYN7OVP39VXKPMY = createForeignKey(com.topscore.omnichannel.order.jooq.Keys.KEY_MEMBER_PRIMARY, Order.ORDER_, "FK414gucur8moyn7ovp39vxkpmy", Order.ORDER_.MEMBER_NUMBER);
        public static final ForeignKey<OrderGoodsRecord, OrderRecord> FKIO4DNP4A0HXMD2C1VJAO7VYT7 = createForeignKey(com.topscore.omnichannel.order.jooq.Keys.KEY_ORDER_PRIMARY, OrderGoods.ORDER_GOODS, "FKio4dnp4a0hxmd2c1vjao7vyt7", OrderGoods.ORDER_GOODS.ORDER_NUMBER, OrderGoods.ORDER_GOODS.ORDER_WRITE_OFF);
        public static final ForeignKey<OrderGoodsRecord, GoodsRecord> FK7IG6A3V9C9ALUSUPY6OYXLFOW = createForeignKey(com.topscore.omnichannel.order.jooq.Keys.KEY_GOODS_PRIMARY, OrderGoods.ORDER_GOODS, "FK7ig6a3v9c9alusupy6oyxlfow", OrderGoods.ORDER_GOODS.GOODS_NUMBER);
    }
}
