/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq;


import com.topscore.omnichannel.order.jooq.tables.Goods;
import com.topscore.omnichannel.order.jooq.tables.Member;
import com.topscore.omnichannel.order.jooq.tables.OrderGoods;
import com.topscore.omnichannel.order.jooq.tables.OrderMessage;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order extends SchemaImpl {

    private static final long serialVersionUID = -1738978858;

    /**
     * The reference instance of <code>order</code>
     */
    public static final Order ORDER = new Order();

    /**
     * The table <code>order.goods</code>.
     */
    public final Goods GOODS = com.topscore.omnichannel.order.jooq.tables.Goods.GOODS;

    /**
     * The table <code>order.member</code>.
     */
    public final Member MEMBER = com.topscore.omnichannel.order.jooq.tables.Member.MEMBER;

    /**
     * The table <code>order.order</code>.
     */
    public final com.topscore.omnichannel.order.jooq.tables.Order ORDER_ = com.topscore.omnichannel.order.jooq.tables.Order.ORDER_;

    /**
     * The table <code>order.order_goods</code>.
     */
    public final OrderGoods ORDER_GOODS = com.topscore.omnichannel.order.jooq.tables.OrderGoods.ORDER_GOODS;

    /**
     * The table <code>order.order_message</code>.
     */
    public final OrderMessage ORDER_MESSAGE = com.topscore.omnichannel.order.jooq.tables.OrderMessage.ORDER_MESSAGE;

    /**
     * No further instances allowed
     */
    private Order() {
        super("order", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Goods.GOODS,
            Member.MEMBER,
            com.topscore.omnichannel.order.jooq.tables.Order.ORDER_,
            OrderGoods.ORDER_GOODS,
            OrderMessage.ORDER_MESSAGE);
    }
}
