/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq;


import com.topscore.omnichannel.order.jooq.tables.Goods;
import com.topscore.omnichannel.order.jooq.tables.Member;
import com.topscore.omnichannel.order.jooq.tables.Order;
import com.topscore.omnichannel.order.jooq.tables.OrderGoods;
import com.topscore.omnichannel.order.jooq.tables.OrderMessage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in order
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>order.goods</code>.
     */
    public static final Goods GOODS = com.topscore.omnichannel.order.jooq.tables.Goods.GOODS;

    /**
     * The table <code>order.member</code>.
     */
    public static final Member MEMBER = com.topscore.omnichannel.order.jooq.tables.Member.MEMBER;

    /**
     * The table <code>order.order</code>.
     */
    public static final Order ORDER_ = com.topscore.omnichannel.order.jooq.tables.Order.ORDER_;

    /**
     * The table <code>order.order_goods</code>.
     */
    public static final OrderGoods ORDER_GOODS = com.topscore.omnichannel.order.jooq.tables.OrderGoods.ORDER_GOODS;

    /**
     * The table <code>order.order_message</code>.
     */
    public static final OrderMessage ORDER_MESSAGE = com.topscore.omnichannel.order.jooq.tables.OrderMessage.ORDER_MESSAGE;
}
