/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq.tables.records;


import com.topscore.omnichannel.order.jooq.tables.OrderGoods;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderGoodsRecord extends UpdatableRecordImpl<OrderGoodsRecord> implements Record4<Integer, Boolean, Integer, String> {

    private static final long serialVersionUID = -297462408;

    /**
     * Setter for <code>order.order_goods.order_number</code>.
     */
    public void setOrderNumber(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.order_goods.order_number</code>.
     */
    public Integer getOrderNumber() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>order.order_goods.order_write_off</code>.
     */
    public void setOrderWriteOff(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.order_goods.order_write_off</code>.
     */
    public Boolean getOrderWriteOff() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>order.order_goods.quality</code>.
     */
    public void setQuality(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.order_goods.quality</code>.
     */
    public Integer getQuality() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>order.order_goods.goods_number</code>.
     */
    public void setGoodsNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.order_goods.goods_number</code>.
     */
    public String getGoodsNumber() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Boolean, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Boolean, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Boolean, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderGoods.ORDER_GOODS.ORDER_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return OrderGoods.ORDER_GOODS.ORDER_WRITE_OFF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrderGoods.ORDER_GOODS.QUALITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OrderGoods.ORDER_GOODS.GOODS_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrderNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getOrderWriteOff();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGoodsNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value1(Integer value) {
        setOrderNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value2(Boolean value) {
        setOrderWriteOff(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value3(Integer value) {
        setQuality(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value4(String value) {
        setGoodsNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord values(Integer value1, Boolean value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderGoodsRecord
     */
    public OrderGoodsRecord() {
        super(OrderGoods.ORDER_GOODS);
    }

    /**
     * Create a detached, initialised OrderGoodsRecord
     */
    public OrderGoodsRecord(Integer orderNumber, Boolean orderWriteOff, Integer quality, String goodsNumber) {
        super(OrderGoods.ORDER_GOODS);

        set(0, orderNumber);
        set(1, orderWriteOff);
        set(2, quality);
        set(3, goodsNumber);
    }
}
