/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq.tables.records;


import com.topscore.omnichannel.order.jooq.tables.OrderMessage;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderMessageRecord extends UpdatableRecordImpl<OrderMessageRecord> implements Record10<String, Integer, String, Timestamp, Timestamp, String, Timestamp, String, Timestamp, Integer> {

    private static final long serialVersionUID = -105684303;

    /**
     * Setter for <code>order.order_message.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.order_message.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>order.order_message.type</code>.
     */
    public void setType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.order_message.type</code>.
     */
    public Integer getType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>order.order_message.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.order_message.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>order.order_message.created_time</code>.
     */
    public void setCreatedTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.order_message.created_time</code>.
     */
    public Timestamp getCreatedTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>order.order_message.sent_time</code>.
     */
    public void setSentTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>order.order_message.sent_time</code>.
     */
    public Timestamp getSentTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>order.order_message.id_card</code>.
     */
    public void setIdCard(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>order.order_message.id_card</code>.
     */
    public String getIdCard() {
        return (String) get(5);
    }

    /**
     * Setter for <code>order.order_message.created_date</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>order.order_message.created_date</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>order.order_message.message</code>.
     */
    public void setMessage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>order.order_message.message</code>.
     */
    public String getMessage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>order.order_message.sent_date</code>.
     */
    public void setSentDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>order.order_message.sent_date</code>.
     */
    public Timestamp getSentDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>order.order_message.source</code>.
     */
    public void setSource(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>order.order_message.source</code>.
     */
    public Integer getSource() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Integer, String, Timestamp, Timestamp, String, Timestamp, String, Timestamp, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Integer, String, Timestamp, Timestamp, String, Timestamp, String, Timestamp, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OrderMessage.ORDER_MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrderMessage.ORDER_MESSAGE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OrderMessage.ORDER_MESSAGE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return OrderMessage.ORDER_MESSAGE.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return OrderMessage.ORDER_MESSAGE.SENT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OrderMessage.ORDER_MESSAGE.ID_CARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return OrderMessage.ORDER_MESSAGE.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return OrderMessage.ORDER_MESSAGE.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return OrderMessage.ORDER_MESSAGE.SENT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return OrderMessage.ORDER_MESSAGE.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getSentTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIdCard();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getSentDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value2(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value4(Timestamp value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value5(Timestamp value) {
        setSentTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value6(String value) {
        setIdCard(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value7(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value8(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value9(Timestamp value) {
        setSentDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord value10(Integer value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderMessageRecord values(String value1, Integer value2, String value3, Timestamp value4, Timestamp value5, String value6, Timestamp value7, String value8, Timestamp value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderMessageRecord
     */
    public OrderMessageRecord() {
        super(OrderMessage.ORDER_MESSAGE);
    }

    /**
     * Create a detached, initialised OrderMessageRecord
     */
    public OrderMessageRecord(String id, Integer type, String content, Timestamp createdTime, Timestamp sentTime, String idCard, Timestamp createdDate, String message, Timestamp sentDate, Integer source) {
        super(OrderMessage.ORDER_MESSAGE);

        set(0, id);
        set(1, type);
        set(2, content);
        set(3, createdTime);
        set(4, sentTime);
        set(5, idCard);
        set(6, createdDate);
        set(7, message);
        set(8, sentDate);
        set(9, source);
    }
}
