/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq.tables.records;


import com.topscore.omnichannel.order.jooq.tables.OrderGoods;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 订单商品表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderGoodsRecord extends UpdatableRecordImpl<OrderGoodsRecord> implements Record4<String, String, Integer, BigDecimal> {

    private static final long serialVersionUID = 321777486;

    /**
     * Setter for <code>order.order_goods.order_id</code>. 订单号
     */
    public void setOrderId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>order.order_goods.order_id</code>. 订单号
     */
    public String getOrderId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>order.order_goods.goods_id</code>. 商品编号
     */
    public void setGoodsId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>order.order_goods.goods_id</code>. 商品编号
     */
    public String getGoodsId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>order.order_goods.quality</code>. 购买数量
     */
    public void setQuality(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>order.order_goods.quality</code>. 购买数量
     */
    public Integer getQuality() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>order.order_goods.unit_price</code>. 单价
     */
    public void setUnitPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>order.order_goods.unit_price</code>. 单价
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Integer, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Integer, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OrderGoods.ORDER_GOODS.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OrderGoods.ORDER_GOODS.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrderGoods.ORDER_GOODS.QUALITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return OrderGoods.ORDER_GOODS.UNIT_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getUnitPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value1(String value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value2(String value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value3(Integer value) {
        setQuality(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value4(BigDecimal value) {
        setUnitPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord values(String value1, String value2, Integer value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderGoodsRecord
     */
    public OrderGoodsRecord() {
        super(OrderGoods.ORDER_GOODS);
    }

    /**
     * Create a detached, initialised OrderGoodsRecord
     */
    public OrderGoodsRecord(String orderId, String goodsId, Integer quality, BigDecimal unitPrice) {
        super(OrderGoods.ORDER_GOODS);

        set(0, orderId);
        set(1, goodsId);
        set(2, quality);
        set(3, unitPrice);
    }
}
