/*
 * This file is generated by jOOQ.
*/
package com.topscore.omnichannel.order.jooq.tables.records;


import com.topscore.omnichannel.order.jooq.tables.OrderGoods;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderGoodsRecord extends UpdatableRecordImpl<OrderGoodsRecord> implements Record4<String, Integer, BigDecimal, String> {

    private static final long serialVersionUID = -936162033;

    /**
     * Setter for <code>orderdb.order_goods.goods_id</code>.
     */
    public void setGoodsId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderdb.order_goods.goods_id</code>.
     */
    public String getGoodsId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>orderdb.order_goods.quality</code>.
     */
    public void setQuality(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderdb.order_goods.quality</code>.
     */
    public Integer getQuality() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>orderdb.order_goods.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>orderdb.order_goods.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>orderdb.order_goods.order_id</code>.
     */
    public void setOrderId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>orderdb.order_goods.order_id</code>.
     */
    public String getOrderId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, BigDecimal, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, BigDecimal, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OrderGoods.ORDER_GOODS.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrderGoods.ORDER_GOODS.QUALITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return OrderGoods.ORDER_GOODS.UNIT_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OrderGoods.ORDER_GOODS.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQuality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getUnitPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value1(String value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value2(Integer value) {
        setQuality(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value3(BigDecimal value) {
        setUnitPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord value4(String value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderGoodsRecord values(String value1, Integer value2, BigDecimal value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderGoodsRecord
     */
    public OrderGoodsRecord() {
        super(OrderGoods.ORDER_GOODS);
    }

    /**
     * Create a detached, initialised OrderGoodsRecord
     */
    public OrderGoodsRecord(String goodsId, Integer quality, BigDecimal unitPrice, String orderId) {
        super(OrderGoods.ORDER_GOODS);

        set(0, goodsId);
        set(1, quality);
        set(2, unitPrice);
        set(3, orderId);
    }
}
